dist: xenial
language: java
os: linux
jdk:
  - openjdk17
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: ocuFMMPDfgho8mlfBC2vbqL6qaizNeA2jPZJfaFIS/ytosJ5KGXbvLc85i0MmBZIKaLJWlgCo1eUeEMUxNgVgOM1yZiTLLEuEDpX4MTqoPUwuYiaozUwtxzMwHar11+O+sKkNUMTd2MbDPwxCwuAnPi39PML+kwyg0IC4tjgB4cR42S77U9k6hBKo2Y+NznmHQIdJ0HSKBCB6fllYiSsry2iwx8cMX1Bd3njlHWKHvtjSKl4rRnpvl6kO4QFPqlBwES7Ae0X5fdlGVo6FS2vbrlKnxY78drzExzo224qyQEPG3DuBJGigMMnAmmG7XmweiaurzzLTfC4g9XwdXAaMndonNwHxnAzcFnh/FtxieSmf34+RTx1HaJcqttoqKVU4KAzPugaPOxu4pweTD1dHIQKYZVPoy//FGowjJuyYYnZREvA9LHPwdelTP1DBd8LisEDw5URzd98666/Nbl8dpMeiyePqLvQoVlzk+I6e5aBMSHiqsh+z9iOCLf8aW43c4rzhMoVqp1P5IBGNOvbWJXICYXPVuXPlZvtnu7Zd7zBlFaotKdZPRgc3T0S1ZcOwLZZezBH23d5asHpQ2xzY/cEtMKFcaNPXhzYrJBx2kvmtBxWN4zUl21AUbs+tqpBpFqNFxs5vDeSoekPuvLXI3wP+H/U5Wu0vJrryzVv/L8=
env:
  global:
    secure: NLQy62gt5uysHwi+Ey6VEUxYdS6R5mSOh3SuN3P/SBR6q7E2vSooqIKRsvbRy8mxkwprFxHQJ8ZcByK/JXdjwH//9ncURHj/ClptmCuYkHryzgVYC6Rlzll59jk2yWyIu+dXZp8cIeqNfcJ3T9hcUyWtk88qxrlytJFyWoAXZpiile6e5Q5uMfhPH/FYgDC5nu3oPSpMZEEPWFXF23vHNJ87PkC4wEl/wpTxl1QTUdYijdRldG625AkW/00bvPN+oukVV/R97G1Ck09Mc1SE/iLp2bXC1xoupMYgp0SfmxS0whZrkMLalYF+jc7+638+0IEvobBbLd+OLjoLsOH/7A7JH/5t6l4Mt7UstK8qX6rCar/6gaDL/BIzwS4Yq9KIr+iQ6WBvqxJOcyHeTTKnGfUGcCDAoSHM3MtvWzBRSG803cSrRgFMqacR43SariNOfLf8W7UZIVhJY9VrpE9pZApW0WBT9IQ3/a5cmwSOvDYkEbKielCGfZw6/QUbbz8j9VZgMi6O8sF/BlpZU/NVWWV9J/pCY3AZOTn/6VGCFsf+uC/vqhgrEx80YwJR1XmG1GiOdTI78ec00wo522MHYBc7Z9kymtCwKA0kmq/Lhuz1tt7Hdorooui3sS+civlionKTA3h6rXnleXyO6tXw4dnUPGeYqMJ5h1l87Dxb2Yo=
